#2023.01.07 This replaces "A" with "B" in field $64
BEGIN {FS=OFS="|"} 
	{
	sub(/^U\. S\. A\.$/, "United States of America", $64) 
	sub(/^Unirted States$/, "United States of America", $64) 
	sub(/^Unite4d States$/, "United States of America", $64) 
	sub(/^United Staets$/, "United States of America", $64) 
	sub(/^United States$/, "United States of America", $64) 
	sub(/^United State$/, "United States of America", $64) 
	sub(/^United states$/, "United States of America", $64) 
	sub(/^Unites states$/, "United States of America", $64) 
	sub(/^Unites States$/, "United States of America", $64) 
	sub(/^United States$/, "United States of America", $64) 
	sub(/^United Stateas$/, "United States of America", $64) 
	sub(/^United Stated$/, "United States of America", $64) 
	sub(/^United STates$/, "United States of America", $64) 
	sub(/^United Sttes$/, "United States of America", $64) 
	sub(/^United S$/, "United States of America", $64) 
	sub(/^Unnited States$/, "United States of America", $64) 
	sub(/^Untied States$/, "United States of America", $64) 
	sub(/^Untied S$/, "United States of America", $64) 
	sub(/^U\.S\.$/, "United States of America", $64) 
	sub(/^US USA$/, "United States of America", $64) 
	sub(/^Usa$/, "United States of America", $64) 
	sub(/^U.S.A.$/, "United States of America", $64) 
	sub(/^U.S.A$/, "United States of America", $64) 
	sub(/^U.S.A.`$/, "United States of America", $64) 
	sub(/^UsA$/, "United States of America", $64) 
	sub(/^UsA$/, "United States of America", $64) 
	sub(/^United States \/ Canada$/, "United States of America \/ Canada", $64) 
	sub(/^United States\/ Canada$/, "United States of America \/ Canada", $64) 
	sub(/^United States\/Canada$/, "United States of America \/ Canada", $64) 
	sub(/^UNITED KINGDOM$/, "United Kingdom", $64) 
	sub(/^URUGUAY$/, "Uruguay", $64) 
	sub(/^US Virgin Islands$/, "U.S. Virgin Islands", $64) 
	sub(/^USSA$/, "United States of America", $64) 
	sub(/^USAA$/, "United States of America", $64) 
	sub(/^USA$/, "United States of America", $64) 
	sub(/^US$/, "United States of America", $64) 
	sub(/^USUA$/, "United States of America", $64) 
	sub(/^USa$/, "United States of America", $64) 
	sub(/^UUSA$/, "United States of America", $64) 
	sub(/^Uraguay$/, "Uruguay", $64) 
	sub(/^uSA$/, "United States of America", $64) 
	sub(/^tats-Unis$/, "United States of America", $64) 
	sub(/^united states$/, "United States of America", $64) 
	sub(/^tats-Unis \[= Canada, confirmed Serge Payette\]$/, "United States of America [= Canada. confirmed Serge Payette]", $64) 
	sub(/^USAA$/, "United States of America", $64); print 
}
